### ISSUE TITLE
Reduce size (~4.5GB) of the container specified in Dockerfile

### ISSUE THREAD

**Issue by AlejandroCN7** [jajimer/energym#19]
It may be interesting to reduce this size. There are some minimal Linux OS variants like Alpine that might work.

**Comment by jajimer** [comment]
I agree. However, almost half of size comes from stable-baselines because it includes PyTorch. Maybe we could create a "light image" with just the basic packages.
We used Ubuntu because [it seems](https://energyplus.net/downloads) is the only Linux platform supported...which is a bit weird.
