### ISSUE TITLE
Execution time test

### ISSUE THREAD

**Issue by jajimer** [jajimer/energym#47]
Since we are adding more and more functionalities into energym, I think we should include a test to measure the execution time of the simulation.

Maybe it is enough to launch some environments with random actions and assert that simulation runs in less than N seconds/steps.

**Comment by AlejandroCN7** [comment]
I think it's a very good idea! I'll keep it in mind.

**Comment by AlejandroCN7** [comment]
How much time we consider a "good" execution time? I think we should consider several factors:

1. Execution time depends on the computer which is used to run simulation specifically.
2. *Eplus-demo-v1* has 3 months of simulation per episode, so it should let less execution time.

**Comment by jajimer** [comment]
I think that criteria is ok! Maybe this shouldn't even be considered as a test. It is just a way to measure the performance of the simulation in order to detect bottlenecks or implementation problems.
For me 30 seconds per year is good, so perfect so far.

**Comment by AlejandroCN7** [comment]
I can design a script to show execution times in terminal (in examples folder, for example) for each env instead of tests. This will allow us to try executions with different combination of wrappers, for example. I'll keep in mind.
